### ISSUE TITLE
Online demo is down

### ISSUE THREAD

**Issue by Stamenov** [decompositional-semantics-initiative/improved-ParaBank-rewriter#1]
Online demo seems to be down.
http://parabank-naacl-2019-rewriter.appspot.com/
![image](https://user-images.githubusercontent.com/1288381/70700580-46ccff00-1ccb-11ea-820f-8eec1330a515.png)

**Comment by vandurme** [comment]
Thank you, we're aware: we are a little stalled in shifting the website over with new pointers, TBD early next week.  Please checkout:

   demo.parabank.io

**Comment by zhyack** [comment]
Is it down again? I cannot open demo.parabank.io.

**Comment by charman** [comment]
The demo is back up.  There appears to be some sort of memory leak that causes the demo to periodically crash that we haven't tracked down yet.  You can also download a Docker image if you want to run the demo on your local machine:

https://hub.docker.com/r/charman/parabank
